### ISSUE TITLE
Injecting to another application requires INJECT_EVENTS permission

### ISSUE THREAD

**Issue by IamTheDefender** [kmille36/scrcpy-audio-support#1]
java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
        at android.os.Parcel.createException(Parcel.java:2360)
        at android.os.Parcel.readException(Parcel.java:2343)
        at android.os.Parcel.readException(Parcel.java:2285)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:1012)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:907)
        at com.android.commands.input.Input.injectKeyEvent(Input.java:355)
        at com.android.commands.input.Input.access$100(Input.java:41)
        at com.android.commands.input.Input$InputKeyEvent.sendKeyEvent(Input.java:203)
        at com.android.commands.input.Input$InputKeyEvent.run(Input.java:190)
        at com.android.commands.input.Input.onRun(Input.java:107)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:60)
        at com.android.commands.input.Input.main(Input.java:71)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:463)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.input.InputManagerService.injectInputEventInternal(InputManagerService.java:790)
        at com.android.server.input.InputManagerService.injectInputEvent(InputManagerService.java:764)
        at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:459)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)

**Comment by kmille36** [comment]
Can you provide screenshot?

**Comment by kmille36** [comment]
Which android version on your phone?

**Comment by kmille36** [comment]
You phone need to  Android 10 or higher for audio support.

**Comment by kmille36** [comment]
Thanks for reporting error. I will add command to check android version, you still can connect to your phone but no audio.

**Comment by IamTheDefender** [comment]
This bug was auto fixed, I just closed the phone screen and connect

**Comment by IamTheDefender** [comment]
This bug was auto fixed, I just closed the phone screen and connect

**Comment by kmille36** [comment]
Ok! Nice!
